version: "2"
services:
  ssp:
    build: .
    volumes:
      # Utilize custom certs 
      - ./development/ssp/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/ssp/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      
      # Configure the debugger
      - ./development/ssp/run-debug.sh:/data/run-debug.sh
    command: ["/data/run-debug.sh"]
    ports:
      - "80:80"
    env_file:
      - ./local.env
    
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.38.0/24
          gateway: 10.20.38.1
